changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
envPrefix: "CHANGIE_"
versionFormat: '## dbt-athena {{.Version}} - {{.Time.Format "January 02, 2006"}}'
kindFormat: '### {{.Kind}}'
changeFormat: |-
    {{- $IssueList := list }}
    {{- $changes := splitList " " $.Custom.Issue }}
    {{- range $issueNbr := $changes }}
        {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-athena/issues/nbr)" | replace "nbr" $issueNbr }}
        {{- $IssueList = append $IssueList $changeLink  }}
    {{- end -}}
    - {{.Body}} ({{ range $index, $element := $IssueList }}{{if $index}}, {{end}}{{$element}}{{end}})
kinds:
-   label: Breaking Changes
-   label: Features
-   label: Fixes
-   label: Under the Hood
-   label: Dependencies
    changeFormat: |-
        {{- $PRList := list }}
        {{- $changes := splitList " " $.Custom.PR }}
        {{- range $pullrequest := $changes }}
            {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-athena/pull/nbr)" | replace "nbr" $pullrequest }}
            {{- $PRList = append $PRList $changeLink  }}
        {{- end -}}
        - {{.Body}} ({{ range $index, $element := $PRList }}{{if $index}}, {{end}}{{$element}}{{end}})
    skipGlobalChoices: true
    additionalChoices:
    -   key: Author
        label: GitHub Username(s) (separated by a single space if multiple)
        type: string
        minLength: 3
    -   key: PR
        label: GitHub Pull Request Number (separated by a single space if multiple)
        type: string
        minLength: 1
-   label: Security
    changeFormat: |-
        {{- $PRList := list }}
        {{- $changes := splitList " " $.Custom.PR }}
        {{- range $pullrequest := $changes }}
            {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-athena/pull/nbr)" | replace "nbr" $pullrequest }}
            {{- $PRList = append $PRList $changeLink  }}
        {{- end -}}
        - {{.Body}} ({{ range $index, $element := $PRList }}{{if $index}}, {{end}}{{$element}}{{end}})
    skipGlobalChoices: true
    additionalChoices:
    -   key: Author
        label: GitHub Username(s) (separated by a single space if multiple)
        type: string
        minLength: 3
    -   key: PR
        label: GitHub Pull Request Number (separated by a single space if multiple)
        type: string
        minLength: 1
newlines:
    afterChangelogHeader: 1
    afterKind: 1
    afterChangelogVersion: 1
    beforeKind: 1
    endOfVersion: 1
custom:
-   key: Author
    label: GitHub Username(s) (separated by a single space if multiple)
    type: string
    minLength: 3
-   key: Issue
    label: GitHub Issue Number (separated by a single space if multiple)
    type: string
    minLength: 1
footerFormat: |
    {{- /* We only want to include non-dbt contributors, so build a list of Core and Adapters maintainers for exclusion */ -}}
    {{- $maintainers := list -}}
    {{- $core_team := splitList " " .Env.CORE_TEAM -}}
    {{- range $team_member := $core_team -}}
        {{- /* ensure all names in this list are all lowercase for later matching purposes */ -}}
        {{- $team_member_lower := lower $team_member -}}
        {{- $maintainers = append $maintainers $team_member_lower -}}
    {{- end -}}

    {{- /* Ensure we always skip dependabot */ -}}
    {{- $maintainers = append $maintainers "dependabot[bot]" -}}

    {{- /* Build the list of contributors along with their PRs */ -}}
    {{- $contributorDict := dict -}}
    {{- range $change := .Changes -}}
        {{- /* PRs can have multiple authors */ -}}
        {{- $authorList := splitList " " $change.Custom.Author -}}

        {{- /* Loop through all non-dbt authors for this changelog */ -}}
        {{- range $author := $authorList -}}
            {{- $authorLower := lower $author -}}
            {{- if not (has $authorLower $maintainers) -}}

                {{- $changeList := splitList " " $change.Custom.Author -}}
                {{- $IssueList := list -}}
                {{- $changeLink := $change.Kind -}}

                {{- /* Build the issue link */ -}}
                {{- if or (eq $change.Kind "Dependencies") (eq $change.Kind "Security") -}}
                    {{- $changes := splitList " " $change.Custom.PR -}}
                    {{- range $issueNbr := $changes -}}
                        {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-athena/pull/nbr)" | replace "nbr" $issueNbr -}}
                        {{- $IssueList = append $IssueList $changeLink -}}
                    {{- end -}}

                {{- else -}}
                    {{- $changes := splitList " " $change.Custom.Issue -}}
                    {{- range $issueNbr := $changes -}}
                        {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-athena/issues/nbr)" | replace "nbr" $issueNbr -}}
                        {{- $IssueList = append $IssueList $changeLink -}}
                    {{- end -}}

                {{- end -}}

                {{- /* If this contributor has other changes associated with them already, add this issue to the list */ -}}
                {{- if hasKey $contributorDict $author -}}
                    {{- $contributionList := get $contributorDict $author -}}
                    {{- $contributionList = concat $contributionList $IssueList -}}
                    {{- $contributorDict := set $contributorDict $author $contributionList -}}

                {{- /* Otherwise create a new entry for this contributor */ -}}
                {{- else -}}
                    {{- $contributionList := $IssueList -}}
                    {{- $contributorDict := set $contributorDict $author $contributionList -}}

                {{- end -}}

            {{- end -}}
        {{- end -}}
    {{- end -}}

    {{- /* no indentation here for formatting so the final markdown doesn't have unneeded indentations */ -}}
    {{- if $contributorDict }}
    ### Contributors
    {{- range $k,$v := $contributorDict }}
    - [@{{ $k }}](https://github.com/{{ $k }}) ({{ range $index, $element := $v }}{{ if $index }}, {{ end }}{{ $element }}{{ end }})
    {{- end }}
    {{- end }}
