CATALOG_ID = "catalog_id"
DATA_CATALOG_NAME = "awsdatacatalog"
SHARED_DATA_CATALOG_NAME = "12345678910"
DATABASE_NAME = "test_dbt_athena"
BUCKET = "test-dbt-athena"
AWS_REGION = "eu-west-1"
S3_STAGING_DIR = "s3://my-bucket/test-dbt/"
ATHENA_WORKGROUP = "dbt-athena-adapter"
